version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: vetapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vetdb
      MYSQL_USER: vetapp
      MYSQL_PASSWORD: vetapp123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "vetapp", "-pvetapp123"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vetapp-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vet-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vetdb?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: vetapp
      SPRING_DATASOURCE_PASSWORD: vetapp123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - vetapp-network

networks:
  vetapp-network:
    driver: bridge

volumes:
  mysql_data: 